services:
  postgresql-testdb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - 7432:5432
    volumes:
      - pgdata:/etc/postgresql/16/main/

  mewingpad-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql-testdb
    environment:
      BACKEND_TYPE: docker
    ports:
      - "5000:80"
  
volumes:
  pgdata: